#!/bin/bash

echo "🚀 手动部署到Vercel指南"
echo "================================"
echo ""
echo "步骤1: 访问Vercel网站"
echo "1. 打开 https://vercel.com"
echo "2. 使用GitHub账户登录"
echo ""
echo "步骤2: 导入项目"
echo "1. 点击 'New Project'"
echo "2. 选择 'Import Git Repository'"
echo "3. 选择仓库: DetachedRepoForChao/englishGraph"
echo ""
echo "步骤3: 配置项目"
echo "Framework Preset: Other"
echo "Root Directory: / (默认)"
echo "Build Command: (留空)"
echo "Output Directory: (留空)"
echo ""
echo "步骤4: 设置环境变量"
echo "NEO4J_URI = neo4j+s://your-instance.databases.neo4j.io"
echo "NEO4J_USERNAME = neo4j"
echo "NEO4J_PASSWORD = Bt-iEdlUwkUHukW4x4yiGbKM0t64n8_l0eWNeN_IwSE"
echo ""
echo "步骤5: 部署"
echo "1. 点击 'Deploy'"
echo "2. 等待部署完成"
echo ""
echo "步骤6: 初始化数据库"
echo "部署完成后，访问: https://your-app.vercel.app/api/init-database"
echo ""
echo "🎉 部署完成！"
